Traceback (most recent call last):
  File "//anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "//anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "//anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "//anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "//anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "//anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "//anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "//anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
[Chi,Chicago_map]=addperson(Chicago_map,Chi,'Jennifer Hudson','Actress',38,'yes','Englewood',60621,41.779699,-87.633194,'worked at Burger King')
Chicago_map
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [Chi,Chicago_map][38;5;241m=[39m[43maddperson[49m[43m([49m[43mChicago_map[49m[43m,[49m[43mChi[49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mJennifer Hudson[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mActress[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;241;43m38[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43myes[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mEnglewood[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;241;43m60621[39;49m[43m,[49m[38;5;241;43m41.779699[39;49m[43m,[49m[38;5;241;43m-[39;49m[38;5;241;43m87.633194[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mworked at Burger King[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m Chicago_map

Cell [0;32mIn[5], line 12[0m, in [0;36maddperson[0;34m(map_name, df, name, age, alive, noted, birth, zipcode, lat, lon, fact)[0m
[1;32m      2[0m our_map[38;5;241m=[39mmap_name 
[1;32m      3[0m new_row [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mName[39m[38;5;124m'[39m:name, 
[1;32m      4[0m                [38;5;124m'[39m[38;5;124mAge[39m[38;5;124m'[39m:age, 
[1;32m      5[0m                [38;5;124m'[39m[38;5;124mAlive[39m[38;5;124m'[39m:alive,
[0;32m   (...)[0m
[1;32m     10[0m                 [38;5;124m'[39m[38;5;124mLon[39m[38;5;124m'[39m:lon,
[1;32m     11[0m                 [38;5;124m'[39m[38;5;124mFun Fact[39m[38;5;124m'[39m:fact            }
[0;32m---> 12[0m df[38;5;241m=[39m [43mdf[49m[38;5;241;43m.[39;49m[43mappend[49m(new_row, ignore_index[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     13[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m df[38;5;241m.[39mindex:
[1;32m     14[0m     p[38;5;241m=[39m[df[38;5;241m.[39mloc[i,[38;5;124m"[39m[38;5;124mLat[39m[38;5;124m"[39m],df[38;5;241m.[39mloc[i,[38;5;124m"[39m[38;5;124mLon[39m[38;5;124m"[39m]]

File [0;32m//anaconda3/lib/python3.10/site-packages/pandas/core/generic.py:5989[0m, in [0;36mNDFrame.__getattr__[0;34m(self, name)[0m
[1;32m   5982[0m [38;5;28;01mif[39;00m (
[1;32m   5983[0m     name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_internal_names_set
[1;32m   5984[0m     [38;5;129;01mand[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_metadata
[1;32m   5985[0m     [38;5;129;01mand[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_accessors
[1;32m   5986[0m     [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_info_axis[38;5;241m.[39m_can_hold_identifiers_and_holds_name(name)
[1;32m   5987[0m ):
[1;32m   5988[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[name]
[0;32m-> 5989[0m [38;5;28;01mreturn[39;00m [38;5;28;43mobject[39;49m[38;5;241;43m.[39;49m[38;5;21;43m__getattribute__[39;49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mname[49m[43m)[49m

[0;31mAttributeError[0m: 'DataFrame' object has no attribute 'append'
AttributeError: 'DataFrame' object has no attribute 'append'

